/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testJsonFileObject(){


        ArrayList<Quotes> quotes= new ArrayList<>();

        try {
            FileReader jsonFile = new FileReader("src/test/resources/recentquotes.json");
            quotes = App.readJson(jsonFile);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }


        assertEquals("Charles Dickens",quotes.get(1).getAuthor());
    }
}
